apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-reply
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
spec:
  ingressClassName: nginx
  rules:
    - host: chat.local
      http:
        paths:
          - path: /reply
            pathType: Prefix
            backend:
              service:
                name: chat-reply
                port:
                  number: 80
